# Site settings
title: This is my Jekyll test
email: dbiringer@integrity-apps.com
description: > # this means to ignore newlines until "baseurl:"
  This project is just being used to get familiar with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  dbiringer

# Build settings
markdown: kramdown
